name: Run Newman API Tests

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure Node.js version >= 16 for Newman

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Postman tests and generate HTML report
      - name: Run Postman tests and generate HTML report
        run: |
          newman run petstore-api.json -e petstore-api-env.json -r html,cli --reporter-html-export newman/newman-report.html

      # Step 5 (Optional): Deploy HTML report to GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: newman
